baseURL = "https://strandtest.netlify.app"
title = "Strandlines"
author = "Stephen James"
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# REMOVE THIS
# themesDir = "../../"
# DO NOT REMOVE THIS
theme = "lanyon"

[Author]
  name = "Stephen James"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "twitter"
  url="https://twitter.com/GoHugoIO"
  icon="fab fa-twitter"

[[params.social]]
title = "rss"
icon = "ti-rss" # themify icon : https://themify.me/themify-icons
link = "https://strandtest.netlify.app/index.xml"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"
  css = ["custom.css"]

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"



[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about section"
    url = "/about/"
    weight = -110

